(function(){'use strict';
const $=window.jQuery; const el=id=>document.getElementById(id);
const state={table:null,loading:false,symbol:'S/.',regimen:'M-RER'};
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
function esc(v){return $('<div>').text(v==null?'':String(v)).html()}
function num(v){const n=Number(v||0);return Number.isFinite(n)?n:0}
function money(v){return `${state.symbol} ${num(v).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function fmtNumber(v){return num(v).toFixed(2)}
function displayDate(iso){if(!iso)return'';const p=iso.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:iso}
function setLoading(on){state.loading=on;el('cpLoading').hidden=!on;el('btnCpGenerate').disabled=on;el('btnCpTxt').disabled=on}
function notify(title,text,icon='warning'){if(window.swal){window.swal({title,text,icon,button:'Aceptar'});}else{alert(`${title}\n${text}`)}}
function regimenLabel(code){return code==='M-RMT'?'Régimen MYPE Tributario':code==='M-RG'?'Régimen General':'Régimen Especial'}
function updateDateLabel(){el('cpDateLabel').textContent=`${displayDate(el('cpFechaInicio').value)} - ${displayDate(el('cpFechaFin').value)}`}
function buildPeriods(selected){const select=el('cpPeriodo');select.innerHTML='';const now=new Date();for(let offset=-36;offset<=3;offset++){const d=new Date(now.getFullYear(),now.getMonth()+offset,1);const value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;const o=document.createElement('option');o.value=value;o.textContent=`${months[d.getMonth()]} del ${d.getFullYear()}`;select.appendChild(o);}if([...select.options].some(o=>o.value===selected))select.value=selected;}
function currentParams(){return new URLSearchParams({fecha_inicio:el('cpFechaInicio').value,fecha_fin:el('cpFechaFin').value,buscar_por:el('cpBuscarPor').value,tipo_documento:el('cpTipoDocumento').value,idsucursal:el('cpSucursal').value,periodo:el('cpPeriodo').value,regimen:state.regimen});}
function validate(){if(!el('cpFechaInicio').value||!el('cpFechaFin').value){notify('Selecciona las fechas','Debes indicar el rango de documentos.');return false}if(el('cpFechaInicio').value>el('cpFechaFin').value){notify('Rango inválido','La fecha inicial no puede ser posterior a la fecha final.');return false}return true}
function statusCell(v){const n=Number(v);return `<span class="cp-state s${n}">${esc(n)}</span>`}
function text(v){return esc(v)} function number(v){return fmtNumber(v)}
function initTable(){state.table=$('#cpTable').DataTable({destroy:true,scrollX:true,scrollCollapse:true,pageLength:10,lengthChange:false,searching:false,ordering:true,order:[],autoWidth:false,dom:'rt<"cp-dt-footer"ip>',columns:[
{data:'periodo',render:text},{data:'cod_unic',render:text},{data:'regimen',render:text},{data:'f_emision',render:text},{data:'f_vencimiento',render:text},{data:'tipo_doc',render:text},{data:'serie',render:text},{data:'dua_dsi',render:text},{data:'numero',render:text},{data:'numero_final',render:text},{data:'t_doc',render:text},{data:'numero_proveedor',render:text},{data:'razon_social',render:text},
{data:'op_gravada',render:number,className:'cp-money'},{data:'igv',render:number,className:'cp-money'},{data:'op_gravada_mixta',render:number,className:'cp-money'},{data:'igv_mixto',render:number,className:'cp-money'},{data:'op_sin_credito',render:number,className:'cp-money'},{data:'igv_sin_credito',render:number,className:'cp-money'},{data:'op_no_gravada',render:number,className:'cp-money'},{data:'isc',render:number,className:'cp-money'},{data:'otros_tributos',render:number,className:'cp-money'},{data:'total',render:number,className:'cp-money'},{data:'moneda',render:text},{data:'tc',render:v=>num(v).toFixed(3),className:'cp-money'},
{data:'fec_comp_modif',render:text},{data:'tipo_doc_modif',render:text},{data:'serie_doc_modif',render:text},{data:'cod_aduana',render:text},{data:'num_doc_modif',render:text},{data:'fec_detraccion',render:text},{data:'num_detraccion',render:text},{data:'retencion',render:text},{data:'clasificacion_bs',render:text},{data:'id_contrato',render:text},{data:'err_tc',render:text},{data:'err_no_habido',render:text},{data:'err_exoneracion',render:text},{data:'err_dni',render:text},{data:'medio_pago',render:text},{data:'estado',render:statusCell}
],createdRow:function(row,data){if(data&&data._fuera_periodo)row.classList.add('cp-row-warning')}});}
function updateSummary(s){s=s||{};el('cpPillCount').textContent=`${Number(s.registros||0)} registro${Number(s.registros||0)===1?'':'s'}`;el('cpPillTotal').textContent=money(s.total||0);el('cpPillIgv').textContent=`IGV ${money(s.igv||0)}`;const w=Number(s.observados||0);el('cpPillWarnings').hidden=w===0;el('cpPillWarnings').textContent=`${w} por revisar`;}
async function bootstrap(){const r=await fetch('Controllers/ContabilidadCompras.php?op=bootstrap',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'No se pudo cargar la configuración.');state.symbol=String(d.empresa?.simbolo||'S/.');const def=d.defaults||{};el('cpFechaInicio').value=def.fecha_inicio||'';el('cpFechaFin').value=def.fecha_fin||'';updateDateLabel();buildPeriods(def.periodo||'');const s=el('cpSucursal');(d.sucursales||[]).forEach(x=>{const o=document.createElement('option');o.value=String(x.idsucursal);o.textContent=x.principal==1?`${x.nombre} · Principal`:x.nombre;s.appendChild(o)});if(Number(def.idsucursal)>0&&[...s.options].some(o=>o.value===String(def.idsucursal)))s.value=String(def.idsucursal);const saved=localStorage.getItem('tiquepos.contabilidad.regimen');if(['M-RER','M-RMT','M-RG'].includes(saved))state.regimen=saved;el('cpBookTitle').textContent=`Libro Elect. Compras / Régimen: ${regimenLabel(state.regimen)}`;}
async function generate(){if(state.loading||!validate())return;setLoading(true);try{const r=await fetch(`Controllers/ContabilidadCompras.php?op=libroCompras&${currentParams()}`,{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'No se pudo generar el reporte.');const rows=Array.isArray(d.data)?d.data:[];state.table.clear().rows.add(rows).draw();updateSummary(d.summary);const branch=el('cpSucursal').options[el('cpSucursal').selectedIndex]?.text||'Todas';el('cpBookMeta').textContent=`${rows.length} registro${rows.length===1?'':'s'} · ${displayDate(el('cpFechaInicio').value)} al ${displayDate(el('cpFechaFin').value)} · ${branch}`;setTimeout(()=>state.table.columns.adjust(),0);}catch(e){console.error(e);notify('No se pudo generar el reporte',e.message||'Ocurrió un error.','error')}finally{setLoading(false)}}
async function downloadTxt(){if(state.loading||!validate())return;setLoading(true);try{const r=await fetch(`Controllers/ContabilidadCompras.php?op=exportarTxtPleCompras&${currentParams()}`,{credentials:'same-origin',cache:'no-store'});if(!r.ok){let msg='No se pudo generar el TXT SUNAT.';try{const d=await r.json();msg=d.message||msg}catch{}throw new Error(msg)}const blob=await r.blob();const cd=r.headers.get('content-disposition')||'';let name='Libro_Compras_PLE_8_1.txt';const m=cd.match(/filename="?([^";]+)"?/i);if(m)name=m[1];const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}catch(e){notify('No se pudo generar el TXT',e.message||'Revisa el período seleccionado.','error')}finally{setLoading(false)}}
function bind(){el('cpDateTrigger').addEventListener('click',e=>{e.stopPropagation();el('cpDatePop').hidden=!el('cpDatePop').hidden});el('cpDatePop').addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',()=>el('cpDatePop').hidden=true);el('cpApplyDates').addEventListener('click',()=>{updateDateLabel();el('cpDatePop').hidden=true});el('cpCurrentMonth').addEventListener('click',()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');el('cpFechaInicio').value=`${y}-${m}-01`;el('cpFechaFin').value=`${y}-${m}-${String(new Date(y,d.getMonth()+1,0).getDate()).padStart(2,'0')}`;updateDateLabel()});el('btnCpGenerate').addEventListener('click',generate);el('btnCpTxt').addEventListener('click',downloadTxt);el('cpPeriodo').addEventListener('change',()=>{el('cpBookMeta').textContent=`Periodo contable: ${el('cpPeriodo').options[el('cpPeriodo').selectedIndex]?.text||''}`});window.addEventListener('resize',()=>{if(state.table)state.table.columns.adjust()});}
$(async function(){try{initTable();bind();await bootstrap();}catch(e){console.error(e);notify('Libro de Compras',e.message||'No se pudo iniciar el módulo.','error')}});
})();
